/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.momentum.multiply.hhs.main;

import java.awt.*;
import java.io.IOException;
import java.util.logging.*;

/**
 *
 * @author zachristophers
 */
public class ApplicationMainFrame extends javax.swing.JFrame {

    
    public FileHandler handler;
    public Logger logger;
    /**
     * Creates new form ApplicationMainFram
     */
    public ApplicationMainFrame() {
        initComponents();
        try {
            handler = new FileHandler("default.log", true);
        } catch (IOException ex) {
            logger = Logger.getLogger("com.momentum.multiply.hhs.logger");
        } catch (SecurityException ex) {
            logger = Logger.getLogger("com.momentum.multiply.hhs.logger");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblMultiply = new javax.swing.JLabel();
        lblTestCentreLogo = new javax.swing.JLabel();
        btnTestHHS = new javax.swing.JButton();
        btnTestFuture1 = new javax.swing.JButton();
        btnTestFuture2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiply Test Center");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMultiply.setBackground(new java.awt.Color(255, 255, 255));
        lblMultiply.setForeground(new java.awt.Color(255, 255, 255));
        lblMultiply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/momentum/multiply/hhs/main/multiply.png"))); // NOI18N
        lblMultiply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMultiply.setOpaque(true);
        lblMultiply.setVisible(true);
        getContentPane().add(lblMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -1, 1600, 625));

        lblTestCentreLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblTestCentreLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblTestCentreLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/momentum/multiply/hhs/main/multiply test centre.png"))); // NOI18N
        lblTestCentreLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTestCentreLogo.setOpaque(true);
        lblTestCentreLogo.setVisible(true);
        getContentPane().add(lblTestCentreLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 125, 600, 400));

        btnTestHHS.setBackground(new java.awt.Color(200, 200, 200));
        btnTestHHS.setForeground(new java.awt.Color(0, 0, 0));
        btnTestHHS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTestHHS.setFont(new Font("Times New Roman", 0, 18));
        btnTestHHS.setText("Test Healthy Heart Score");
        btnTestHHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestHHSActionPerformed(evt);
            }
        });
        btnTestHHS.setEnabled(false);
        getContentPane().add(btnTestHHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, 40));

        lblMultiply.setVisible(true);
        this.getContentPane().setBackground(Color.white);
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationMainFrame().setVisible(true);
            }
        });

        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ApplicationMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        postSleepOperation();
    }

    public static void postSleepOperation() {
        lblMultiply.setVisible(false);
        btnTestHHS.setEnabled(true);
    }

    private void btnTestHHSActionPerformed(java.awt.event.ActionEvent evt) {
        new HHSTestStationFrame(this).setVisible(true);
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(ApplicationMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }

    // Variables declaration - do not modify                     
    protected static javax.swing.JLabel lblMultiply;
    private static javax.swing.JLabel lblTestCentreLogo;
    private static javax.swing.JButton btnTestHHS;
    private javax.swing.JButton btnTestFuture1;
    private javax.swing.JButton btnTestFuture2;
    // End of variables declaration                   
}
